---
- name: KABOOM!
  hosts: all
  
  tasks:
  
  - name: Prior Modifications
    cmd: TOMCAT="$(ls -v apache-tomcat-*.gz | tail -n 1)" && sed -i "s|\(apache-tomcat-\).*|$TOMCAT|g" Dockerfile
      chdir: /home/kalyan/tomcat
      
  - name: Same thing stupid
    shell: JAVA="$(ls -v jdk-*.gz | tail -n 1)" && sed -i "s|\(jdk-\).*|$JAVA|g" Dockerfile
      chdir: /home/kalyan/tomcat
  
  - name: Build an image and push it to a private repo
  docker_image:
    build:
      path: /home/kalyan/tomcat
    name: whatever/whocare
    tag: v1
    push: no
    source: build
